apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: fast
  namespace: monitoring
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
allowVolumeExpansion: true
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: data-volume-1
  namespace: monitoring
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-test-cluster-8d1ed-pvc-96f9e809-8120-11e9-bb68-42010a94005f
